Module6 task3
htmlacademy-react/352625-six-cities-7 pull request #12
Opened 2021-06-28 19:56 UTC by twelwet

Реализовал обработку асинхронных ошибок приема/отправки данных на сервер как смог.
Никак не могу понять как подступиться к решению фичей типа:
Пока форма отправляется ее нужно заблокировать, в случае успешной отправки - очистить поля, в случае неуспеха - разблокировать форму, поля не очищать.

2021-06-29 13:53 UTC, balesniy requested changes
- стандартный подход для решения "Пока форма отправляется ее нужно заблокировать" - хранить состояние isFetching, перед стартом запроса устанавливать его в true и снимать при ответе/ошибке, и научить интерфейс реагировать на это состояние блокировкой формы
- прямолинейное решение для очистки формы после ответа - слушать промис из асинхронного действия, дальше можно будет порефакторить - например оформить отдельный хук

2021-06-29 13:53 UTC, balesniy commented on project/src/components/pages/room/room.jsx
> +  if (Object.keys(offer).length === 0 || neighborOffers.length === 0 || reviews.length === 0) {
тут нужно поправить логику, если у объявления нет reviews или neighborOffers, то мы не увидим страницу, можно завести флаг типа isLoaded и привязать спинер к нему

2021-06-29 13:53 UTC, balesniy commented on project/src/components/ui/comment-form/comment-form.jsx
> +    saveReview(review);
мы можем вернуть промис из асинхронного действия и привязать очистку формы к его выполнению

2021-06-29 13:53 UTC, balesniy commented on project/src/components/ui/comment-form/comment-form.jsx
>          <p className="reviews__help">
мы уже можем привязать блокировку кнопки к состоянию полей - реализовать минимальную валидацию на клиенте

2021-06-29 13:53 UTC, balesniy commented on project/src/components/ui/comment-form/comment-form.jsx
> +    dispatch(fetchComments(data.offerId));
асинхронные действия выполнятся в произвольном порядке, мы можем не получить актуальный список комментариев, при этом сервер на POST /comments/: hotel_id отвечает актуальным списков комментов, можно отдельно его не запрашивать, достаточно сохранить ответ

2021-06-29 13:53 UTC, balesniy commented on project/src/components/ui/reviews/review/review.jsx
> +  const monthByLetters = months[adaptedDate.getMonth()];
посмотри на метод toLocaleString

2021-07-09 15:22 UTC, balesniy approved these changes
отличная работа! 👍 
у меня несколько замечаний по стилю, следующий модуль будет про рефакторинг, там можно будет редьюсеры поправить

2021-07-09 15:22 UTC, balesniy commented on project/src/components/pages/room/room.jsx
> +      setIsErrorsExist(true);
выглядит избыточно, пропс копируется в состояние

2021-07-09 15:22 UTC, balesniy commented on project/src/components/pages/room/room.jsx
> +    // TODO Надо как-то упростить
тут Status.IDLE выглядит лишним для показа загрузчика и снова копия пропс в состояние

2021-07-09 15:22 UTC, balesniy commented on project/src/components/ui/comment-form/comment-form.jsx
> +const minCommentLength = 50;
константа

2021-07-09 15:22 UTC, balesniy commented on project/src/components/ui/comment-form/comment-form.jsx
> +          disabled={(review.comment.length < minCommentLength || review.rating === null || userComment.status === Status.PENDING) ? true : ''}
тут лишний тернарный

2021-07-09 15:23 UTC, merged

2021-07-10 10:43 UTC, twelwet commented on project/src/components/ui/notification/notification.jsx
> +  );
Читаю демку про useEffect (https://up.htmlacademy.ru/react/7/demos/5387#10):
"...Передача пустого массива (отсутствия зависимостей) фактически говорит, что зависимостей никаких нет. А раз их нет, то значит функцию с эффектом (которую мы передали useEffect) следует выполнить лишь при монтировании компонента. Если в компоненте изменится состояние, то повторного применения эффекта не будет. Таким образом, мы получаем поведение, аналогичное componentDidMount."
Наверное и в данном случае требуется только установить пустой массив вторым параметром useEffect?

2021-07-10 11:56 UTC, balesniy commented on project/src/components/ui/notification/notification.jsx
> +  );
да, если мы хотим один раз показать сообщение, то нужен пустой массив, а если мы захотим при изменении message перезавести таймер, то укажем его.