Module3 task1
htmlacademy-react/352625-six-cities-7 pull request #5
Opened 2021-06-09 19:03 UTC by twelwet

Есть один вопрос: при запуске приложения в браузерную консоль прилетает Warning:
"Warning: Received `true` for a non-boolean attribute `href`." и стек вызовов.
Сколько не искал в коде - не смог найти где же у меня ссылка имеет href="true".
В чем может быть проблема? Может быть дело в компоненте <Link/>, которым частично заменил стандартные теги ссылок.

2021-06-10 12:14 UTC, balesniy commented
> Есть один вопрос: при запуске приложения в браузерную консоль прилетает Warning:
> "Warning: Received `true` for a non-boolean attribute `href`." и стек вызовов.
> Сколько не искал в коде - не смог найти где же у меня ссылка имеет href="true".

посмотри вот тут https://ru.reactjs.org/docs/jsx-in-depth.html#props-default-to-true , при этом href="true" будет строкой, и ворнинга не будет, в разметке есть ссылки с пустым href, это валидный html, но в jsx получается ворнинг, похожая ситуация с tabIndex - передаешь строку, а Dom-элемент ждет число. смотри на jsx не как на html а как на работу с элементами из js, тогда появляется логика, типа disabled=true это нормально а href=true уже нет

2021-06-10 12:26 UTC, balesniy reviewed
https://github.com/htmlacademy-react/352625-six-cities-7/pull/5/files#diff-958a20b4130de94d2c0ba70229f9edcba81e6c036969fc03c7c38ea830969e27R34 - вот тут пустой href, вообще такое глазами трудно найти, ide + typescript помогают

2021-06-10 12:26 UTC, balesniy commented on project/src/components/pages/room/room.jsx
> +  const [offer] = offers.filter((item) => item.id === id);
тут скорее нужен метод find

2021-06-10 12:26 UTC, balesniy commented on project/src/components/ui/comment-form/comment-form.jsx
> +        <input
звездочки просят цикла, и чтобы сделать их управляемыми нужно явно задать checked для текущей

2021-06-10 12:26 UTC, balesniy commented on project/src/components/ui/comment-form/comment-form.jsx
> +        onChange={handleFieldChange}
для управляемого поля формы нужно задать value, см пример в https://ru.reactjs.org/docs/forms.html#the-textarea-tag

2021-06-10 12:37 UTC, balesniy requested changes

2021-06-10 12:37 UTC, balesniy commented on project/src/components/ui/offer-card-favourites/offer-card-favourites.jsx
> +    <article className="favorites__card place-card">
карточки насколько я вижу отличаются только классами в паре блоков, попробуй собрать их в один компонент и передавать тип параметром, вроде `<OfferCard type="favourites">`

2021-06-10 12:37 UTC, balesniy commented on project/src/components/ui/offer-card-favourites/offer-card-favourites.jsx
> +          <a href={'/'}>{description}</a>
"клик по заголовку карточки предложения должен переводить пользователя на страницу «Room»" - нам уже нужна перелинковка

2021-06-10 12:37 UTC, balesniy commented on project/src/components/ui/offers-list/offers-list.jsx
> +  const [activeOffer, setActiveOfferId] = useState({activeOfferId: null});
для одного поля можно не создавать объект состояния, useState позволяет нам хранить отдельные значения

2021-06-10 12:37 UTC, balesniy commented on project/src/components/ui/offers-list/offers-list.jsx
> +import offersPropTypes from '../../../prop-types/offers.prop';
можно научить сборщик резолвить пути от корня, https://create-react-app.dev/docs/importing-a-component/#absolute-imports

2021-06-11 10:21 UTC, balesniy approved these changes
отметил несколько шероховатостей, попробуй с ними разобраться перед следующим заданием

2021-06-11 10:21 UTC, balesniy commented on project/src/components/pages/room/room.jsx
> +    return <NotFound/>;
эту логику лучше вынести на уровень роутера для наглядности

2021-06-11 10:21 UTC, balesniy commented on project/src/components/pages/room/room.jsx
>    );
тут можно переиспользовать компонент карточки

2021-06-11 10:21 UTC, balesniy commented on project/src/components/ui/offer-card/offer-card.jsx
> +      onMouseEnter={cardType === 'original' ? onOfferHover : () => {}}
дефолтные значения лучше вынести в параметры функции для наглядности

2021-06-11 10:21 UTC, balesniy commented on project/src/components/ui/offer-card/offer-card.jsx
> +        <div className={isPremium ? 'place-card__mark' : 'visually-hidden'}>
Premium может быть на любой странице

2021-06-11 10:21 UTC, balesniy commented on project/src/components/ui/offer-card/offer-card.jsx
> +  cardType: PropTypes.string,
для необязательных параметров нужно задать дефолтные значения для стабильной работы компонента

2021-06-11 10:21 UTC, balesniy commented on project/src/components/ui/rating-star/rating-star.jsx
> +  weight: PropTypes.number,
не забывай про required, при таком объявлении не очень понятно, управляемый компонент или нет, если передать weight но забыть про changeHandler то компонент сломается

2021-06-11 10:21 UTC, balesniy commented on project/src/utils/gets-stars-list.js
> +  do {
на мой взгляд, использование императивного цикла не оправдано, критерий про методы-итераторы у вас убрали, но стилистически такое решение для получения натурального ряда чисел выбивается, методы массивов позволяют описать задачу декларативно

2021-06-11 10:21 UTC, merged

2021-06-15 09:34 UTC, twelwet commented on project/src/components/pages/room/room.jsx
>    );
Структура верстки <div className="property__wrapper"> слишком сильно отличается от компонента карточки.

2021-06-15 09:54 UTC, balesniy commented on project/src/components/pages/room/room.jsx
>    );
я вижу только дополнительные классы, что я пропустил?

2021-06-15 10:40 UTC, twelwet commented on project/src/components/pages/room/room.jsx
>    );
Может быть я что-то не допонял.
Компонент карточки offer-card.jsx имеет следующую структуру:
    article .place-card
      div .place-card__mark
      div .place-card__image-wrapper
      div .place-card__info
        div .place-card__price-wrapper
          div .place-card__price
          .button .place-card__bookmark-button
        div .place-card__rating
        h2 .place-card__name
        p .place-card__type
А блок верстки в room.jsx имеет иную структуру элементов:
    div .property__wrapper
      div .property__mark
      div .property__name-wrapper
        h1 .property__name
        button .property__bookmark-button
      div .property__rating
      ul .property__features
      div .property__price
      div .property__inside
      div .property__host
      section .property__reviews

2021-06-15 10:54 UTC, twelwet commented on project/src/components/pages/room/room.jsx
>    );
Может быть я что-то не допонял.
Компонент карточки offer-card.jsx имеет следующую структуру:
|  article .place-card
|    div .place-card__mark
|    div .place-card__image-wrapper
|    div .place-card__info
|      div .place-card__price-wrapper
|        div .place-card__price
|        button .place-card__bookmark-button
|      div .place-card__rating
|      h2 .place-card__name
|      p .place-card__type

А блок верстки в room.jsx имеет иную структуру элементов:
|  div .property__wrapper
|    div .property__mark
|    div .property__name-wrapper
|      h1 .property__name
|      button .property__bookmark-button
|    div .property__rating
|    ul .property__features
|    div .property__price
|    div .property__inside
|    div .property__host
|    section .property__reviews

2021-06-15 11:00 UTC, twelwet commented on project/src/components/pages/room/room.jsx
>    );
Может быть я что-то не допонял.
Компонент карточки offer-card.jsx имеет следующую структуру:
|--article .place-card
|----div .place-card__mark
|----div .place-card__image-wrapper
|----div .place-card__info
|------div .place-card__price-wrapper
|------div .place-card__price
|--------button .place-card__bookmark-button
|--------div .place-card__rating
|------h2 .place-card__name
|------p .place-card__type

А блок верстки в room.jsx имеет иную структуру элементов:
|--div .property__wrapper
|----div .property__mark
|----div .property__name-wrapper
|------h1 .property__name
|------button .property__bookmark-button
|----div .property__rating
|----ul .property__features
|----div .property__price
|------b .property__price-value
|------span .property__price-text
|----div .property__inside
|----div .property__host
|----section .property__reviews

2021-06-15 11:31 UTC, balesniy commented on project/src/components/pages/room/room.jsx
>    );
я про блок Other places in the neighbourhood - там обычные place-card с доп классами

2021-06-15 11:51 UTC, twelwet commented on project/src/components/pages/room/room.jsx
>    );
Понятно, хорошо - поправлю.