Module4 task1
htmlacademy-react/352625-six-cities-7 pull request #6
Opened 2021-06-16 08:22 UTC by twelwet

2021-06-17 07:38 UTC, balesniy requested changes
с базовым подключением карты хорошо получилось, теперь нужно оптимизировать хуки, чтобы подготовить компонент к обновлениям

2021-06-17 07:38 UTC, balesniy commented on project/src/components/pages/favourites/favourites.jsx
> +                <ListFavourites offers={offers}/>
список предложений нужно предварительно распределить по городам, тут получится вложенная структура

2021-06-17 07:38 UTC, balesniy commented on project/src/components/ui/offers-list/list-favourites/list-favourites.jsx
> +          .filter((offer) => offer.isBookmark === true)
эту логику лучше сразу вынести из компонента "повыше", у нас в теории есть отдельный список избранного на сервере

2021-06-17 07:38 UTC, balesniy commented on project/src/utils/gets-stars-list.js
> +    .map((item, index) => item - index);
👍

2021-06-17 07:38 UTC, balesniy commented on project/src/components/ui/map/map.jsx
> +  });
в useEffect вторым параметром нужно передавать массив зависимостей, иначе он будет выполняться при каждом рендере компонента, и добавлять маркеры на карту, см в доке https://ru.reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects

2021-06-17 07:38 UTC, balesniy commented on project/src/components/ui/map/init-map.js
> +const City = {
город нужно передать в пропсах компонента

2021-06-17 07:38 UTC, balesniy commented on project/src/components/ui/map/map.jsx
> +    const {map, icon} = initMap();
инициализация нам нужна только один раз, при монтировании компонента, сейчас initMap будет вызван при каждом изменении, посмотри у вас есть отличная демка по использованию хуков и карты - https://up.htmlacademy.ru/react/7/demos/5509#1 - можно прям оттуда взять решение

2021-06-18 17:14 UTC, balesniy approved these changes
- с шаблонами все готово, осталось поправить рандомные ключи в списках
- карта инициализируются корректно, но маркеры на ней копятся. список предложений у нас будет меняться при смене города, это уже в следующем модуле, а в каком задании нам предлагают активный подсветить я не нашел, так что сейчас забираю так, нам в любом случае нужно будет менять центровку карты, там же тогда и лишние маркеры поправим, посмотри пока демку про очистку эффекта

2021-06-18 17:15 UTC, merged

2021-06-18 19:56 UTC, twelwet commented on project/src/components/ui/offers-list/list-main/list-main.jsx
>                  onOfferHover={() => setActiveOfferId(offer.id)}
Если передать коллбек "как есть":
|--ListMain
|----onOfferHover={setActiveOfferId}
|----onOfferLeave={resetActiveOfferId}
то анонимную функцию '{() => setActiveOfferId(offer.id)}' придется все равно вызывать уже не из ListMain, а из Main:
|--Main
|----setActiveOfferId={() => setActiveOfferId(offer.id)} <-- Как в Main получить доступ к offer.id ?
|----resetActiveOfferId={() => setActiveOfferId(null)}

Может быть я что-то не допонял?

2021-06-18 20:00 UTC, balesniy commented on project/src/components/ui/offers-list/list-main/list-main.jsx
>                  onOfferHover={() => setActiveOfferId(offer.id)}
она вызывается в "самом низу" на дом-элементе в карточке, а раз в карточке есть id, то можно не создавать промежуточных функций, достаточно одного колбэка

2021-06-18 20:10 UTC, twelwet commented on project/src/components/ui/map/map.jsx
> +  }, [map, offers, icon, iconActive, activeOfferId]);
Здесь не совсем понял, можешь поподробнее описать задачу данной логики?

2021-06-18 20:14 UTC, balesniy commented on project/src/components/ui/map/map.jsx
> +  }, [map, offers, icon, iconActive, activeOfferId]);
задача - очистить маркеры перед добавлением новых, можно просто все удалить